package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceLiveQw generated by hbm2java
 */
public class AutoRaceLiveQw implements java.io.Serializable {

	private AutoRaceLiveQwId id;
	private Boolean isFinal;
	private BigDecimal qwmin12;
	private BigDecimal qwmax12;
	private BigDecimal qwmin13;
	private BigDecimal qwmax13;
	private BigDecimal qwmin14;
	private BigDecimal qwmax14;
	private BigDecimal qwmin15;
	private BigDecimal qwmax15;
	private BigDecimal qwmin16;
	private BigDecimal qwmax16;
	private BigDecimal qwmin17;
	private BigDecimal qwmax17;
	private BigDecimal qwmin18;
	private BigDecimal qwmax18;
	private BigDecimal qwmin23;
	private BigDecimal qwmax23;
	private BigDecimal qwmin24;
	private BigDecimal qwmax24;
	private BigDecimal qwmin25;
	private BigDecimal qwmax25;
	private BigDecimal qwmin26;
	private BigDecimal qwmax26;
	private BigDecimal qwmin27;
	private BigDecimal qwmax27;
	private BigDecimal qwmin28;
	private BigDecimal qwmax28;
	private BigDecimal qwmin34;
	private BigDecimal qwmax34;
	private BigDecimal qwmin35;
	private BigDecimal qwmax35;
	private BigDecimal qwmin36;
	private BigDecimal qwmax36;
	private BigDecimal qwmin37;
	private BigDecimal qwmax37;
	private BigDecimal qwmin38;
	private BigDecimal qwmax38;
	private BigDecimal qwmin45;
	private BigDecimal qwmax45;
	private BigDecimal qwmin46;
	private BigDecimal qwmax46;
	private BigDecimal qwmin47;
	private BigDecimal qwmax47;
	private BigDecimal qwmin48;
	private BigDecimal qwmax48;
	private BigDecimal qwmin56;
	private BigDecimal qwmax56;
	private BigDecimal qwmin57;
	private BigDecimal qwmax57;
	private BigDecimal qwmin58;
	private BigDecimal qwmax58;
	private BigDecimal qwmin67;
	private BigDecimal qwmax67;
	private BigDecimal qwmin68;
	private BigDecimal qwmax68;
	private BigDecimal qwmin78;
	private BigDecimal qwmax78;
	private Date extractTime;
	private Boolean corruptedOdds;
	private Integer sales;
	private Integer returnSales;
	private Integer netsales;

	public AutoRaceLiveQw() {
	}

	public AutoRaceLiveQw(AutoRaceLiveQwId id) {
		this.id = id;
	}

	public AutoRaceLiveQw(AutoRaceLiveQwId id, Boolean isFinal,
			BigDecimal qwmin12, BigDecimal qwmax12, BigDecimal qwmin13,
			BigDecimal qwmax13, BigDecimal qwmin14, BigDecimal qwmax14,
			BigDecimal qwmin15, BigDecimal qwmax15, BigDecimal qwmin16,
			BigDecimal qwmax16, BigDecimal qwmin17, BigDecimal qwmax17,
			BigDecimal qwmin18, BigDecimal qwmax18, BigDecimal qwmin23,
			BigDecimal qwmax23, BigDecimal qwmin24, BigDecimal qwmax24,
			BigDecimal qwmin25, BigDecimal qwmax25, BigDecimal qwmin26,
			BigDecimal qwmax26, BigDecimal qwmin27, BigDecimal qwmax27,
			BigDecimal qwmin28, BigDecimal qwmax28, BigDecimal qwmin34,
			BigDecimal qwmax34, BigDecimal qwmin35, BigDecimal qwmax35,
			BigDecimal qwmin36, BigDecimal qwmax36, BigDecimal qwmin37,
			BigDecimal qwmax37, BigDecimal qwmin38, BigDecimal qwmax38,
			BigDecimal qwmin45, BigDecimal qwmax45, BigDecimal qwmin46,
			BigDecimal qwmax46, BigDecimal qwmin47, BigDecimal qwmax47,
			BigDecimal qwmin48, BigDecimal qwmax48, BigDecimal qwmin56,
			BigDecimal qwmax56, BigDecimal qwmin57, BigDecimal qwmax57,
			BigDecimal qwmin58, BigDecimal qwmax58, BigDecimal qwmin67,
			BigDecimal qwmax67, BigDecimal qwmin68, BigDecimal qwmax68,
			BigDecimal qwmin78, BigDecimal qwmax78, Date extractTime,
			Boolean corruptedOdds, Integer sales, Integer returnSales,
			Integer netsales) {
		this.id = id;
		this.isFinal = isFinal;
		this.qwmin12 = qwmin12;
		this.qwmax12 = qwmax12;
		this.qwmin13 = qwmin13;
		this.qwmax13 = qwmax13;
		this.qwmin14 = qwmin14;
		this.qwmax14 = qwmax14;
		this.qwmin15 = qwmin15;
		this.qwmax15 = qwmax15;
		this.qwmin16 = qwmin16;
		this.qwmax16 = qwmax16;
		this.qwmin17 = qwmin17;
		this.qwmax17 = qwmax17;
		this.qwmin18 = qwmin18;
		this.qwmax18 = qwmax18;
		this.qwmin23 = qwmin23;
		this.qwmax23 = qwmax23;
		this.qwmin24 = qwmin24;
		this.qwmax24 = qwmax24;
		this.qwmin25 = qwmin25;
		this.qwmax25 = qwmax25;
		this.qwmin26 = qwmin26;
		this.qwmax26 = qwmax26;
		this.qwmin27 = qwmin27;
		this.qwmax27 = qwmax27;
		this.qwmin28 = qwmin28;
		this.qwmax28 = qwmax28;
		this.qwmin34 = qwmin34;
		this.qwmax34 = qwmax34;
		this.qwmin35 = qwmin35;
		this.qwmax35 = qwmax35;
		this.qwmin36 = qwmin36;
		this.qwmax36 = qwmax36;
		this.qwmin37 = qwmin37;
		this.qwmax37 = qwmax37;
		this.qwmin38 = qwmin38;
		this.qwmax38 = qwmax38;
		this.qwmin45 = qwmin45;
		this.qwmax45 = qwmax45;
		this.qwmin46 = qwmin46;
		this.qwmax46 = qwmax46;
		this.qwmin47 = qwmin47;
		this.qwmax47 = qwmax47;
		this.qwmin48 = qwmin48;
		this.qwmax48 = qwmax48;
		this.qwmin56 = qwmin56;
		this.qwmax56 = qwmax56;
		this.qwmin57 = qwmin57;
		this.qwmax57 = qwmax57;
		this.qwmin58 = qwmin58;
		this.qwmax58 = qwmax58;
		this.qwmin67 = qwmin67;
		this.qwmax67 = qwmax67;
		this.qwmin68 = qwmin68;
		this.qwmax68 = qwmax68;
		this.qwmin78 = qwmin78;
		this.qwmax78 = qwmax78;
		this.extractTime = extractTime;
		this.corruptedOdds = corruptedOdds;
		this.sales = sales;
		this.returnSales = returnSales;
		this.netsales = netsales;
	}

	public AutoRaceLiveQwId getId() {
		return this.id;
	}

	public void setId(AutoRaceLiveQwId id) {
		this.id = id;
	}

	public Boolean getIsFinal() {
		return this.isFinal;
	}

	public void setIsFinal(Boolean isFinal) {
		this.isFinal = isFinal;
	}

	public BigDecimal getQwmin12() {
		return this.qwmin12;
	}

	public void setQwmin12(BigDecimal qwmin12) {
		this.qwmin12 = qwmin12;
	}

	public BigDecimal getQwmax12() {
		return this.qwmax12;
	}

	public void setQwmax12(BigDecimal qwmax12) {
		this.qwmax12 = qwmax12;
	}

	public BigDecimal getQwmin13() {
		return this.qwmin13;
	}

	public void setQwmin13(BigDecimal qwmin13) {
		this.qwmin13 = qwmin13;
	}

	public BigDecimal getQwmax13() {
		return this.qwmax13;
	}

	public void setQwmax13(BigDecimal qwmax13) {
		this.qwmax13 = qwmax13;
	}

	public BigDecimal getQwmin14() {
		return this.qwmin14;
	}

	public void setQwmin14(BigDecimal qwmin14) {
		this.qwmin14 = qwmin14;
	}

	public BigDecimal getQwmax14() {
		return this.qwmax14;
	}

	public void setQwmax14(BigDecimal qwmax14) {
		this.qwmax14 = qwmax14;
	}

	public BigDecimal getQwmin15() {
		return this.qwmin15;
	}

	public void setQwmin15(BigDecimal qwmin15) {
		this.qwmin15 = qwmin15;
	}

	public BigDecimal getQwmax15() {
		return this.qwmax15;
	}

	public void setQwmax15(BigDecimal qwmax15) {
		this.qwmax15 = qwmax15;
	}

	public BigDecimal getQwmin16() {
		return this.qwmin16;
	}

	public void setQwmin16(BigDecimal qwmin16) {
		this.qwmin16 = qwmin16;
	}

	public BigDecimal getQwmax16() {
		return this.qwmax16;
	}

	public void setQwmax16(BigDecimal qwmax16) {
		this.qwmax16 = qwmax16;
	}

	public BigDecimal getQwmin17() {
		return this.qwmin17;
	}

	public void setQwmin17(BigDecimal qwmin17) {
		this.qwmin17 = qwmin17;
	}

	public BigDecimal getQwmax17() {
		return this.qwmax17;
	}

	public void setQwmax17(BigDecimal qwmax17) {
		this.qwmax17 = qwmax17;
	}

	public BigDecimal getQwmin18() {
		return this.qwmin18;
	}

	public void setQwmin18(BigDecimal qwmin18) {
		this.qwmin18 = qwmin18;
	}

	public BigDecimal getQwmax18() {
		return this.qwmax18;
	}

	public void setQwmax18(BigDecimal qwmax18) {
		this.qwmax18 = qwmax18;
	}

	public BigDecimal getQwmin23() {
		return this.qwmin23;
	}

	public void setQwmin23(BigDecimal qwmin23) {
		this.qwmin23 = qwmin23;
	}

	public BigDecimal getQwmax23() {
		return this.qwmax23;
	}

	public void setQwmax23(BigDecimal qwmax23) {
		this.qwmax23 = qwmax23;
	}

	public BigDecimal getQwmin24() {
		return this.qwmin24;
	}

	public void setQwmin24(BigDecimal qwmin24) {
		this.qwmin24 = qwmin24;
	}

	public BigDecimal getQwmax24() {
		return this.qwmax24;
	}

	public void setQwmax24(BigDecimal qwmax24) {
		this.qwmax24 = qwmax24;
	}

	public BigDecimal getQwmin25() {
		return this.qwmin25;
	}

	public void setQwmin25(BigDecimal qwmin25) {
		this.qwmin25 = qwmin25;
	}

	public BigDecimal getQwmax25() {
		return this.qwmax25;
	}

	public void setQwmax25(BigDecimal qwmax25) {
		this.qwmax25 = qwmax25;
	}

	public BigDecimal getQwmin26() {
		return this.qwmin26;
	}

	public void setQwmin26(BigDecimal qwmin26) {
		this.qwmin26 = qwmin26;
	}

	public BigDecimal getQwmax26() {
		return this.qwmax26;
	}

	public void setQwmax26(BigDecimal qwmax26) {
		this.qwmax26 = qwmax26;
	}

	public BigDecimal getQwmin27() {
		return this.qwmin27;
	}

	public void setQwmin27(BigDecimal qwmin27) {
		this.qwmin27 = qwmin27;
	}

	public BigDecimal getQwmax27() {
		return this.qwmax27;
	}

	public void setQwmax27(BigDecimal qwmax27) {
		this.qwmax27 = qwmax27;
	}

	public BigDecimal getQwmin28() {
		return this.qwmin28;
	}

	public void setQwmin28(BigDecimal qwmin28) {
		this.qwmin28 = qwmin28;
	}

	public BigDecimal getQwmax28() {
		return this.qwmax28;
	}

	public void setQwmax28(BigDecimal qwmax28) {
		this.qwmax28 = qwmax28;
	}

	public BigDecimal getQwmin34() {
		return this.qwmin34;
	}

	public void setQwmin34(BigDecimal qwmin34) {
		this.qwmin34 = qwmin34;
	}

	public BigDecimal getQwmax34() {
		return this.qwmax34;
	}

	public void setQwmax34(BigDecimal qwmax34) {
		this.qwmax34 = qwmax34;
	}

	public BigDecimal getQwmin35() {
		return this.qwmin35;
	}

	public void setQwmin35(BigDecimal qwmin35) {
		this.qwmin35 = qwmin35;
	}

	public BigDecimal getQwmax35() {
		return this.qwmax35;
	}

	public void setQwmax35(BigDecimal qwmax35) {
		this.qwmax35 = qwmax35;
	}

	public BigDecimal getQwmin36() {
		return this.qwmin36;
	}

	public void setQwmin36(BigDecimal qwmin36) {
		this.qwmin36 = qwmin36;
	}

	public BigDecimal getQwmax36() {
		return this.qwmax36;
	}

	public void setQwmax36(BigDecimal qwmax36) {
		this.qwmax36 = qwmax36;
	}

	public BigDecimal getQwmin37() {
		return this.qwmin37;
	}

	public void setQwmin37(BigDecimal qwmin37) {
		this.qwmin37 = qwmin37;
	}

	public BigDecimal getQwmax37() {
		return this.qwmax37;
	}

	public void setQwmax37(BigDecimal qwmax37) {
		this.qwmax37 = qwmax37;
	}

	public BigDecimal getQwmin38() {
		return this.qwmin38;
	}

	public void setQwmin38(BigDecimal qwmin38) {
		this.qwmin38 = qwmin38;
	}

	public BigDecimal getQwmax38() {
		return this.qwmax38;
	}

	public void setQwmax38(BigDecimal qwmax38) {
		this.qwmax38 = qwmax38;
	}

	public BigDecimal getQwmin45() {
		return this.qwmin45;
	}

	public void setQwmin45(BigDecimal qwmin45) {
		this.qwmin45 = qwmin45;
	}

	public BigDecimal getQwmax45() {
		return this.qwmax45;
	}

	public void setQwmax45(BigDecimal qwmax45) {
		this.qwmax45 = qwmax45;
	}

	public BigDecimal getQwmin46() {
		return this.qwmin46;
	}

	public void setQwmin46(BigDecimal qwmin46) {
		this.qwmin46 = qwmin46;
	}

	public BigDecimal getQwmax46() {
		return this.qwmax46;
	}

	public void setQwmax46(BigDecimal qwmax46) {
		this.qwmax46 = qwmax46;
	}

	public BigDecimal getQwmin47() {
		return this.qwmin47;
	}

	public void setQwmin47(BigDecimal qwmin47) {
		this.qwmin47 = qwmin47;
	}

	public BigDecimal getQwmax47() {
		return this.qwmax47;
	}

	public void setQwmax47(BigDecimal qwmax47) {
		this.qwmax47 = qwmax47;
	}

	public BigDecimal getQwmin48() {
		return this.qwmin48;
	}

	public void setQwmin48(BigDecimal qwmin48) {
		this.qwmin48 = qwmin48;
	}

	public BigDecimal getQwmax48() {
		return this.qwmax48;
	}

	public void setQwmax48(BigDecimal qwmax48) {
		this.qwmax48 = qwmax48;
	}

	public BigDecimal getQwmin56() {
		return this.qwmin56;
	}

	public void setQwmin56(BigDecimal qwmin56) {
		this.qwmin56 = qwmin56;
	}

	public BigDecimal getQwmax56() {
		return this.qwmax56;
	}

	public void setQwmax56(BigDecimal qwmax56) {
		this.qwmax56 = qwmax56;
	}

	public BigDecimal getQwmin57() {
		return this.qwmin57;
	}

	public void setQwmin57(BigDecimal qwmin57) {
		this.qwmin57 = qwmin57;
	}

	public BigDecimal getQwmax57() {
		return this.qwmax57;
	}

	public void setQwmax57(BigDecimal qwmax57) {
		this.qwmax57 = qwmax57;
	}

	public BigDecimal getQwmin58() {
		return this.qwmin58;
	}

	public void setQwmin58(BigDecimal qwmin58) {
		this.qwmin58 = qwmin58;
	}

	public BigDecimal getQwmax58() {
		return this.qwmax58;
	}

	public void setQwmax58(BigDecimal qwmax58) {
		this.qwmax58 = qwmax58;
	}

	public BigDecimal getQwmin67() {
		return this.qwmin67;
	}

	public void setQwmin67(BigDecimal qwmin67) {
		this.qwmin67 = qwmin67;
	}

	public BigDecimal getQwmax67() {
		return this.qwmax67;
	}

	public void setQwmax67(BigDecimal qwmax67) {
		this.qwmax67 = qwmax67;
	}

	public BigDecimal getQwmin68() {
		return this.qwmin68;
	}

	public void setQwmin68(BigDecimal qwmin68) {
		this.qwmin68 = qwmin68;
	}

	public BigDecimal getQwmax68() {
		return this.qwmax68;
	}

	public void setQwmax68(BigDecimal qwmax68) {
		this.qwmax68 = qwmax68;
	}

	public BigDecimal getQwmin78() {
		return this.qwmin78;
	}

	public void setQwmin78(BigDecimal qwmin78) {
		this.qwmin78 = qwmin78;
	}

	public BigDecimal getQwmax78() {
		return this.qwmax78;
	}

	public void setQwmax78(BigDecimal qwmax78) {
		this.qwmax78 = qwmax78;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public Boolean getCorruptedOdds() {
		return this.corruptedOdds;
	}

	public void setCorruptedOdds(Boolean corruptedOdds) {
		this.corruptedOdds = corruptedOdds;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getReturnSales() {
		return this.returnSales;
	}

	public void setReturnSales(Integer returnSales) {
		this.returnSales = returnSales;
	}

	public Integer getNetsales() {
		return this.netsales;
	}

	public void setNetsales(Integer netsales) {
		this.netsales = netsales;
	}

}
