package jp.autorace.dc;

// Generated 2015-10-17 10:47:54 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRacePreRacePlayerForcast generated by hbm2java
 */
public class AutoRacePreRacePlayerForcast implements java.io.Serializable {

	private AutoRacePreRacePlayerForcastId id;
	private Long uraceId;
	private Byte clothNo;
	private String forcastVisual;
	private String forcastFine;
	private String forcastRain;
	private String forcastStrength;
	private Date extractTime;

	public AutoRacePreRacePlayerForcast() {
	}

	public AutoRacePreRacePlayerForcast(AutoRacePreRacePlayerForcastId id) {
		this.id = id;
	}

	public AutoRacePreRacePlayerForcast(AutoRacePreRacePlayerForcastId id,
			Long uraceId, Byte clothNo, 
			String forcastVisual, String forcastFine, String forcastRain,
			String forcastStrength) {
		this.id = id;
		this.uraceId = uraceId;
		this.clothNo = clothNo;
		this.forcastVisual = forcastVisual;
		this.forcastFine = forcastFine;
		this.forcastRain = forcastRain;
		this.forcastStrength = forcastStrength;
	}
	
	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public AutoRacePreRacePlayerForcastId getId() {
		return this.id;
	}

	public void setId(AutoRacePreRacePlayerForcastId id) {
		this.id = id;
	}

	public Long getUraceId() {
		return this.uraceId;
	}

	public void setUraceId(Long uraceId) {
		this.uraceId = uraceId;
	}

	public Byte getClothNo() {
		return this.clothNo;
	}

	public void setClothNo(Byte clothNo) {
		this.clothNo = clothNo;
	}

	public String getForcastVisual() {
		return this.forcastVisual;
	}

	public void setForcastVisual(String forcastVisual) {
		this.forcastVisual = forcastVisual;
	}

	public String getForcastFine() {
		return this.forcastFine;
	}

	public void setForcastFine(String forcastFine) {
		this.forcastFine = forcastFine;
	}

	public String getForcastRain() {
		return this.forcastRain;
	}

	public void setForcastRain(String forcastRain) {
		this.forcastRain = forcastRain;
	}

	public String getForcastStrength() {
		return this.forcastStrength;
	}

	public void setForcastStrength(String forcastStrength) {
		this.forcastStrength = forcastStrength;
	}

}
