package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceDividend generated by hbm2java
 */
public class AutoRaceDividend implements java.io.Serializable {

	private AutoRaceDividendId id;
	private Long uraceId;
	private Date raceDate;
	private String betTypeName;
	private Byte comb1;
	private Byte comb2;
	private Byte comb3;
	private BigDecimal dividend;
	private BigDecimal popularity;
	private Date extractTime;

	public AutoRaceDividend() {
	}

	public AutoRaceDividend(AutoRaceDividendId id) {
		this.id = id;
	}

	public AutoRaceDividend(AutoRaceDividendId id, Long uraceId, Date raceDate,
			String betTypeName, Byte comb1, Byte comb2, Byte comb3,
			BigDecimal dividend, BigDecimal popularity, Date extractTime) {
		this.id = id;
		this.uraceId = uraceId;
		this.raceDate = raceDate;
		this.betTypeName = betTypeName;
		this.comb1 = comb1;
		this.comb2 = comb2;
		this.comb3 = comb3;
		this.dividend = dividend;
		this.popularity = popularity;
		this.extractTime = extractTime;
	}

	public AutoRaceDividendId getId() {
		return this.id;
	}

	public void setId(AutoRaceDividendId id) {
		this.id = id;
	}

	public Long getUraceId() {
		return this.uraceId;
	}

	public void setUraceId(Long uraceId) {
		this.uraceId = uraceId;
	}

	public Date getRaceDate() {
		return this.raceDate;
	}

	public void setRaceDate(Date raceDate) {
		this.raceDate = raceDate;
	}

	public String getBetTypeName() {
		return this.betTypeName;
	}

	public void setBetTypeName(String betTypeName) {
		this.betTypeName = betTypeName;
	}

	public Byte getComb1() {
		return this.comb1;
	}

	public void setComb1(Byte comb1) {
		this.comb1 = comb1;
	}

	public Byte getComb2() {
		return this.comb2;
	}

	public void setComb2(Byte comb2) {
		this.comb2 = comb2;
	}

	public Byte getComb3() {
		return this.comb3;
	}

	public void setComb3(Byte comb3) {
		this.comb3 = comb3;
	}

	public BigDecimal getDividend() {
		return this.dividend;
	}

	public void setDividend(BigDecimal dividend) {
		this.dividend = dividend;
	}

	public BigDecimal getPopularity() {
		return this.popularity;
	}

	public void setPopularity(BigDecimal popularity) {
		this.popularity = popularity;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

}
