package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceLiveQ generated by hbm2java
 */
public class AutoRaceLiveQ implements java.io.Serializable {

	private AutoRaceLiveQId id;
	private Boolean isFinal;
	private BigDecimal q12;
	private BigDecimal q13;
	private BigDecimal q14;
	private BigDecimal q15;
	private BigDecimal q16;
	private BigDecimal q17;
	private BigDecimal q18;
	private BigDecimal q23;
	private BigDecimal q24;
	private BigDecimal q25;
	private BigDecimal q26;
	private BigDecimal q27;
	private BigDecimal q28;
	private BigDecimal q34;
	private BigDecimal q35;
	private BigDecimal q36;
	private BigDecimal q37;
	private BigDecimal q38;
	private BigDecimal q45;
	private BigDecimal q46;
	private BigDecimal q47;
	private BigDecimal q48;
	private BigDecimal q56;
	private BigDecimal q57;
	private BigDecimal q58;
	private BigDecimal q67;
	private BigDecimal q68;
	private BigDecimal q78;
	private Date extractTime;
	private Boolean corruptedOdds;
	private Integer sales;
	private Integer returnSales;
	private Integer netsales;

	public AutoRaceLiveQ() {
	}

	public AutoRaceLiveQ(AutoRaceLiveQId id) {
		this.id = id;
	}

	public AutoRaceLiveQ(AutoRaceLiveQId id, Boolean isFinal, BigDecimal q12,
			BigDecimal q13, BigDecimal q14, BigDecimal q15, BigDecimal q16,
			BigDecimal q17, BigDecimal q18, BigDecimal q23, BigDecimal q24,
			BigDecimal q25, BigDecimal q26, BigDecimal q27, BigDecimal q28,
			BigDecimal q34, BigDecimal q35, BigDecimal q36, BigDecimal q37,
			BigDecimal q38, BigDecimal q45, BigDecimal q46, BigDecimal q47,
			BigDecimal q48, BigDecimal q56, BigDecimal q57, BigDecimal q58,
			BigDecimal q67, BigDecimal q68, BigDecimal q78, Date extractTime,
			Boolean corruptedOdds, Integer sales, Integer returnSales,
			Integer netsales) {
		this.id = id;
		this.isFinal = isFinal;
		this.q12 = q12;
		this.q13 = q13;
		this.q14 = q14;
		this.q15 = q15;
		this.q16 = q16;
		this.q17 = q17;
		this.q18 = q18;
		this.q23 = q23;
		this.q24 = q24;
		this.q25 = q25;
		this.q26 = q26;
		this.q27 = q27;
		this.q28 = q28;
		this.q34 = q34;
		this.q35 = q35;
		this.q36 = q36;
		this.q37 = q37;
		this.q38 = q38;
		this.q45 = q45;
		this.q46 = q46;
		this.q47 = q47;
		this.q48 = q48;
		this.q56 = q56;
		this.q57 = q57;
		this.q58 = q58;
		this.q67 = q67;
		this.q68 = q68;
		this.q78 = q78;
		this.extractTime = extractTime;
		this.corruptedOdds = corruptedOdds;
		this.sales = sales;
		this.returnSales = returnSales;
		this.netsales = netsales;
	}

	public AutoRaceLiveQId getId() {
		return this.id;
	}

	public void setId(AutoRaceLiveQId id) {
		this.id = id;
	}

	public Boolean getIsFinal() {
		return this.isFinal;
	}

	public void setIsFinal(Boolean isFinal) {
		this.isFinal = isFinal;
	}

	public BigDecimal getQ12() {
		return this.q12;
	}

	public void setQ12(BigDecimal q12) {
		this.q12 = q12;
	}

	public BigDecimal getQ13() {
		return this.q13;
	}

	public void setQ13(BigDecimal q13) {
		this.q13 = q13;
	}

	public BigDecimal getQ14() {
		return this.q14;
	}

	public void setQ14(BigDecimal q14) {
		this.q14 = q14;
	}

	public BigDecimal getQ15() {
		return this.q15;
	}

	public void setQ15(BigDecimal q15) {
		this.q15 = q15;
	}

	public BigDecimal getQ16() {
		return this.q16;
	}

	public void setQ16(BigDecimal q16) {
		this.q16 = q16;
	}

	public BigDecimal getQ17() {
		return this.q17;
	}

	public void setQ17(BigDecimal q17) {
		this.q17 = q17;
	}

	public BigDecimal getQ18() {
		return this.q18;
	}

	public void setQ18(BigDecimal q18) {
		this.q18 = q18;
	}

	public BigDecimal getQ23() {
		return this.q23;
	}

	public void setQ23(BigDecimal q23) {
		this.q23 = q23;
	}

	public BigDecimal getQ24() {
		return this.q24;
	}

	public void setQ24(BigDecimal q24) {
		this.q24 = q24;
	}

	public BigDecimal getQ25() {
		return this.q25;
	}

	public void setQ25(BigDecimal q25) {
		this.q25 = q25;
	}

	public BigDecimal getQ26() {
		return this.q26;
	}

	public void setQ26(BigDecimal q26) {
		this.q26 = q26;
	}

	public BigDecimal getQ27() {
		return this.q27;
	}

	public void setQ27(BigDecimal q27) {
		this.q27 = q27;
	}

	public BigDecimal getQ28() {
		return this.q28;
	}

	public void setQ28(BigDecimal q28) {
		this.q28 = q28;
	}

	public BigDecimal getQ34() {
		return this.q34;
	}

	public void setQ34(BigDecimal q34) {
		this.q34 = q34;
	}

	public BigDecimal getQ35() {
		return this.q35;
	}

	public void setQ35(BigDecimal q35) {
		this.q35 = q35;
	}

	public BigDecimal getQ36() {
		return this.q36;
	}

	public void setQ36(BigDecimal q36) {
		this.q36 = q36;
	}

	public BigDecimal getQ37() {
		return this.q37;
	}

	public void setQ37(BigDecimal q37) {
		this.q37 = q37;
	}

	public BigDecimal getQ38() {
		return this.q38;
	}

	public void setQ38(BigDecimal q38) {
		this.q38 = q38;
	}

	public BigDecimal getQ45() {
		return this.q45;
	}

	public void setQ45(BigDecimal q45) {
		this.q45 = q45;
	}

	public BigDecimal getQ46() {
		return this.q46;
	}

	public void setQ46(BigDecimal q46) {
		this.q46 = q46;
	}

	public BigDecimal getQ47() {
		return this.q47;
	}

	public void setQ47(BigDecimal q47) {
		this.q47 = q47;
	}

	public BigDecimal getQ48() {
		return this.q48;
	}

	public void setQ48(BigDecimal q48) {
		this.q48 = q48;
	}

	public BigDecimal getQ56() {
		return this.q56;
	}

	public void setQ56(BigDecimal q56) {
		this.q56 = q56;
	}

	public BigDecimal getQ57() {
		return this.q57;
	}

	public void setQ57(BigDecimal q57) {
		this.q57 = q57;
	}

	public BigDecimal getQ58() {
		return this.q58;
	}

	public void setQ58(BigDecimal q58) {
		this.q58 = q58;
	}

	public BigDecimal getQ67() {
		return this.q67;
	}

	public void setQ67(BigDecimal q67) {
		this.q67 = q67;
	}

	public BigDecimal getQ68() {
		return this.q68;
	}

	public void setQ68(BigDecimal q68) {
		this.q68 = q68;
	}

	public BigDecimal getQ78() {
		return this.q78;
	}

	public void setQ78(BigDecimal q78) {
		this.q78 = q78;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public Boolean getCorruptedOdds() {
		return this.corruptedOdds;
	}

	public void setCorruptedOdds(Boolean corruptedOdds) {
		this.corruptedOdds = corruptedOdds;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getReturnSales() {
		return this.returnSales;
	}

	public void setReturnSales(Integer returnSales) {
		this.returnSales = returnSales;
	}

	public Integer getNetsales() {
		return this.netsales;
	}

	public void setNetsales(Integer netsales) {
		this.netsales = netsales;
	}

}
