package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRacePostRacePlayer generated by hbm2java
 */
public class AutoRacePostRacePlayer implements java.io.Serializable {

	private AutoRacePostRacePlayerId id;
	private Long uraceId;
	private String playerName;
	private String playerNameEn;
	private Byte clothNo;
	private Byte finishPosition;
	private String accidentName;
	private BigDecimal handicap;
	private String motorName;
	private BigDecimal trialRunT;
	private BigDecimal raceRunT;
	private BigDecimal st;
	private String startRemark;
	private Boolean scratch;
	private Date extractTime;

	public AutoRacePostRacePlayer() {
	}

	public AutoRacePostRacePlayer(AutoRacePostRacePlayerId id) {
		this.id = id;
	}

	public AutoRacePostRacePlayer(AutoRacePostRacePlayerId id, Long uraceId,
			String playerName, String playerNameEn, Byte clothNo,
			Byte finishPosition, String accidentName, BigDecimal handicap,
			String motorName, BigDecimal trialRunT, BigDecimal raceRunT,
			BigDecimal st, String startRemark, Boolean scratch, Date extractTime) {
		this.id = id;
		this.uraceId = uraceId;
		this.playerName = playerName;
		this.playerNameEn = playerNameEn;
		this.clothNo = clothNo;
		this.finishPosition = finishPosition;
		this.accidentName = accidentName;
		this.handicap = handicap;
		this.motorName = motorName;
		this.trialRunT = trialRunT;
		this.raceRunT = raceRunT;
		this.st = st;
		this.startRemark = startRemark;
		this.scratch = scratch;
		this.extractTime = extractTime;
	}

	public AutoRacePostRacePlayerId getId() {
		return this.id;
	}

	public void setId(AutoRacePostRacePlayerId id) {
		this.id = id;
	}

	public Long getUraceId() {
		return this.uraceId;
	}

	public void setUraceId(Long uraceId) {
		this.uraceId = uraceId;
	}

	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	public String getPlayerNameEn() {
		return this.playerNameEn;
	}

	public void setPlayerNameEn(String playerNameEn) {
		this.playerNameEn = playerNameEn;
	}

	public Byte getClothNo() {
		return this.clothNo;
	}

	public void setClothNo(Byte clothNo) {
		this.clothNo = clothNo;
	}

	public Byte getFinishPosition() {
		return this.finishPosition;
	}

	public void setFinishPosition(Byte finishPosition) {
		this.finishPosition = finishPosition;
	}

	public String getAccidentName() {
		return this.accidentName;
	}

	public void setAccidentName(String accidentName) {
		this.accidentName = accidentName;
	}

	public BigDecimal getHandicap() {
		return this.handicap;
	}

	public void setHandicap(BigDecimal handicap) {
		this.handicap = handicap;
	}

	public String getMotorName() {
		return this.motorName;
	}

	public void setMotorName(String motorName) {
		this.motorName = motorName;
	}

	public BigDecimal getTrialRunT() {
		return this.trialRunT;
	}

	public void setTrialRunT(BigDecimal trialRunT) {
		this.trialRunT = trialRunT;
	}

	public BigDecimal getRaceRunT() {
		return this.raceRunT;
	}

	public void setRaceRunT(BigDecimal raceRunT) {
		this.raceRunT = raceRunT;
	}

	public BigDecimal getSt() {
		return this.st;
	}

	public void setSt(BigDecimal st) {
		this.st = st;
	}

	public String getStartRemark() {
		return this.startRemark;
	}

	public void setStartRemark(String startRemark) {
		this.startRemark = startRemark;
	}

	public Boolean getScratch() {
		return this.scratch;
	}

	public void setScratch(Boolean scratch) {
		this.scratch = scratch;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	@Override
	public String toString() {
		return "AutoRacePostRacePlayer [id=" + id + ", uraceId=" + uraceId
				+ ", playerName=" + playerName + ", playerNameEn="
				+ playerNameEn + ", clothNo=" + clothNo + ", finishPosition="
				+ finishPosition + ", accidentName=" + accidentName
				+ ", handicap=" + handicap + ", motorName=" + motorName
				+ ", trialRunT=" + trialRunT + ", raceRunT=" + raceRunT
				+ ", st=" + st + ", startRemark=" + startRemark + ", scratch="
				+ scratch + ", extractTime=" + extractTime + "]";
	}

}
