package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

/**
 * AutoRaceFinalTiId generated by hbm2java
 */
public class AutoRaceFinalTiId implements java.io.Serializable {

	private long raceId;
	private byte clothNo;

	public AutoRaceFinalTiId() {
	}

	public AutoRaceFinalTiId(long raceId, byte clothNo) {
		this.raceId = raceId;
		this.clothNo = clothNo;
	}

	public long getRaceId() {
		return this.raceId;
	}

	public void setRaceId(long raceId) {
		this.raceId = raceId;
	}

	public byte getClothNo() {
		return this.clothNo;
	}

	public void setClothNo(byte clothNo) {
		this.clothNo = clothNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutoRaceFinalTiId))
			return false;
		AutoRaceFinalTiId castOther = (AutoRaceFinalTiId) other;

		return (this.getRaceId() == castOther.getRaceId())
				&& (this.getClothNo() == castOther.getClothNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRaceId();
		result = 37 * result + this.getClothNo();
		return result;
	}

}
