package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceLiveT generated by hbm2java
 */
public class AutoRaceLiveT implements java.io.Serializable {

	private AutoRaceLiveTId id;
	private Boolean isFinal;
	private BigDecimal h123;
	private BigDecimal h124;
	private BigDecimal h125;
	private BigDecimal h126;
	private BigDecimal h127;
	private BigDecimal h128;
	private BigDecimal h134;
	private BigDecimal h135;
	private BigDecimal h136;
	private BigDecimal h137;
	private BigDecimal h138;
	private BigDecimal h145;
	private BigDecimal h146;
	private BigDecimal h147;
	private BigDecimal h148;
	private BigDecimal h156;
	private BigDecimal h157;
	private BigDecimal h158;
	private BigDecimal h167;
	private BigDecimal h168;
	private BigDecimal h178;
	private BigDecimal h234;
	private BigDecimal h235;
	private BigDecimal h236;
	private BigDecimal h237;
	private BigDecimal h238;
	private BigDecimal h245;
	private BigDecimal h246;
	private BigDecimal h247;
	private BigDecimal h248;
	private BigDecimal h256;
	private BigDecimal h257;
	private BigDecimal h258;
	private BigDecimal h267;
	private BigDecimal h268;
	private BigDecimal h278;
	private BigDecimal h345;
	private BigDecimal h346;
	private BigDecimal h347;
	private BigDecimal h348;
	private BigDecimal h356;
	private BigDecimal h357;
	private BigDecimal h358;
	private BigDecimal h367;
	private BigDecimal h368;
	private BigDecimal h378;
	private BigDecimal h456;
	private BigDecimal h457;
	private BigDecimal h458;
	private BigDecimal h467;
	private BigDecimal h468;
	private BigDecimal h478;
	private BigDecimal h567;
	private BigDecimal h568;
	private BigDecimal h578;
	private BigDecimal h678;
	private Date extractTime;
	private Boolean corruptedOdds;
	private Integer sales;
	private Integer returnSales;
	private Integer netsales;

	public AutoRaceLiveT() {
	}

	public AutoRaceLiveT(AutoRaceLiveTId id) {
		this.id = id;
	}

	public AutoRaceLiveT(AutoRaceLiveTId id, Boolean isFinal, BigDecimal h123,
			BigDecimal h124, BigDecimal h125, BigDecimal h126, BigDecimal h127,
			BigDecimal h128, BigDecimal h134, BigDecimal h135, BigDecimal h136,
			BigDecimal h137, BigDecimal h138, BigDecimal h145, BigDecimal h146,
			BigDecimal h147, BigDecimal h148, BigDecimal h156, BigDecimal h157,
			BigDecimal h158, BigDecimal h167, BigDecimal h168, BigDecimal h178,
			BigDecimal h234, BigDecimal h235, BigDecimal h236, BigDecimal h237,
			BigDecimal h238, BigDecimal h245, BigDecimal h246, BigDecimal h247,
			BigDecimal h248, BigDecimal h256, BigDecimal h257, BigDecimal h258,
			BigDecimal h267, BigDecimal h268, BigDecimal h278, BigDecimal h345,
			BigDecimal h346, BigDecimal h347, BigDecimal h348, BigDecimal h356,
			BigDecimal h357, BigDecimal h358, BigDecimal h367, BigDecimal h368,
			BigDecimal h378, BigDecimal h456, BigDecimal h457, BigDecimal h458,
			BigDecimal h467, BigDecimal h468, BigDecimal h478, BigDecimal h567,
			BigDecimal h568, BigDecimal h578, BigDecimal h678,
			Date extractTime, Boolean corruptedOdds, Integer sales,
			Integer returnSales, Integer netsales) {
		this.id = id;
		this.isFinal = isFinal;
		this.h123 = h123;
		this.h124 = h124;
		this.h125 = h125;
		this.h126 = h126;
		this.h127 = h127;
		this.h128 = h128;
		this.h134 = h134;
		this.h135 = h135;
		this.h136 = h136;
		this.h137 = h137;
		this.h138 = h138;
		this.h145 = h145;
		this.h146 = h146;
		this.h147 = h147;
		this.h148 = h148;
		this.h156 = h156;
		this.h157 = h157;
		this.h158 = h158;
		this.h167 = h167;
		this.h168 = h168;
		this.h178 = h178;
		this.h234 = h234;
		this.h235 = h235;
		this.h236 = h236;
		this.h237 = h237;
		this.h238 = h238;
		this.h245 = h245;
		this.h246 = h246;
		this.h247 = h247;
		this.h248 = h248;
		this.h256 = h256;
		this.h257 = h257;
		this.h258 = h258;
		this.h267 = h267;
		this.h268 = h268;
		this.h278 = h278;
		this.h345 = h345;
		this.h346 = h346;
		this.h347 = h347;
		this.h348 = h348;
		this.h356 = h356;
		this.h357 = h357;
		this.h358 = h358;
		this.h367 = h367;
		this.h368 = h368;
		this.h378 = h378;
		this.h456 = h456;
		this.h457 = h457;
		this.h458 = h458;
		this.h467 = h467;
		this.h468 = h468;
		this.h478 = h478;
		this.h567 = h567;
		this.h568 = h568;
		this.h578 = h578;
		this.h678 = h678;
		this.extractTime = extractTime;
		this.corruptedOdds = corruptedOdds;
		this.sales = sales;
		this.returnSales = returnSales;
		this.netsales = netsales;
	}

	public AutoRaceLiveTId getId() {
		return this.id;
	}

	public void setId(AutoRaceLiveTId id) {
		this.id = id;
	}

	public Boolean getIsFinal() {
		return this.isFinal;
	}

	public void setIsFinal(Boolean isFinal) {
		this.isFinal = isFinal;
	}

	public BigDecimal getH123() {
		return this.h123;
	}

	public void setH123(BigDecimal h123) {
		this.h123 = h123;
	}

	public BigDecimal getH124() {
		return this.h124;
	}

	public void setH124(BigDecimal h124) {
		this.h124 = h124;
	}

	public BigDecimal getH125() {
		return this.h125;
	}

	public void setH125(BigDecimal h125) {
		this.h125 = h125;
	}

	public BigDecimal getH126() {
		return this.h126;
	}

	public void setH126(BigDecimal h126) {
		this.h126 = h126;
	}

	public BigDecimal getH127() {
		return this.h127;
	}

	public void setH127(BigDecimal h127) {
		this.h127 = h127;
	}

	public BigDecimal getH128() {
		return this.h128;
	}

	public void setH128(BigDecimal h128) {
		this.h128 = h128;
	}

	public BigDecimal getH134() {
		return this.h134;
	}

	public void setH134(BigDecimal h134) {
		this.h134 = h134;
	}

	public BigDecimal getH135() {
		return this.h135;
	}

	public void setH135(BigDecimal h135) {
		this.h135 = h135;
	}

	public BigDecimal getH136() {
		return this.h136;
	}

	public void setH136(BigDecimal h136) {
		this.h136 = h136;
	}

	public BigDecimal getH137() {
		return this.h137;
	}

	public void setH137(BigDecimal h137) {
		this.h137 = h137;
	}

	public BigDecimal getH138() {
		return this.h138;
	}

	public void setH138(BigDecimal h138) {
		this.h138 = h138;
	}

	public BigDecimal getH145() {
		return this.h145;
	}

	public void setH145(BigDecimal h145) {
		this.h145 = h145;
	}

	public BigDecimal getH146() {
		return this.h146;
	}

	public void setH146(BigDecimal h146) {
		this.h146 = h146;
	}

	public BigDecimal getH147() {
		return this.h147;
	}

	public void setH147(BigDecimal h147) {
		this.h147 = h147;
	}

	public BigDecimal getH148() {
		return this.h148;
	}

	public void setH148(BigDecimal h148) {
		this.h148 = h148;
	}

	public BigDecimal getH156() {
		return this.h156;
	}

	public void setH156(BigDecimal h156) {
		this.h156 = h156;
	}

	public BigDecimal getH157() {
		return this.h157;
	}

	public void setH157(BigDecimal h157) {
		this.h157 = h157;
	}

	public BigDecimal getH158() {
		return this.h158;
	}

	public void setH158(BigDecimal h158) {
		this.h158 = h158;
	}

	public BigDecimal getH167() {
		return this.h167;
	}

	public void setH167(BigDecimal h167) {
		this.h167 = h167;
	}

	public BigDecimal getH168() {
		return this.h168;
	}

	public void setH168(BigDecimal h168) {
		this.h168 = h168;
	}

	public BigDecimal getH178() {
		return this.h178;
	}

	public void setH178(BigDecimal h178) {
		this.h178 = h178;
	}

	public BigDecimal getH234() {
		return this.h234;
	}

	public void setH234(BigDecimal h234) {
		this.h234 = h234;
	}

	public BigDecimal getH235() {
		return this.h235;
	}

	public void setH235(BigDecimal h235) {
		this.h235 = h235;
	}

	public BigDecimal getH236() {
		return this.h236;
	}

	public void setH236(BigDecimal h236) {
		this.h236 = h236;
	}

	public BigDecimal getH237() {
		return this.h237;
	}

	public void setH237(BigDecimal h237) {
		this.h237 = h237;
	}

	public BigDecimal getH238() {
		return this.h238;
	}

	public void setH238(BigDecimal h238) {
		this.h238 = h238;
	}

	public BigDecimal getH245() {
		return this.h245;
	}

	public void setH245(BigDecimal h245) {
		this.h245 = h245;
	}

	public BigDecimal getH246() {
		return this.h246;
	}

	public void setH246(BigDecimal h246) {
		this.h246 = h246;
	}

	public BigDecimal getH247() {
		return this.h247;
	}

	public void setH247(BigDecimal h247) {
		this.h247 = h247;
	}

	public BigDecimal getH248() {
		return this.h248;
	}

	public void setH248(BigDecimal h248) {
		this.h248 = h248;
	}

	public BigDecimal getH256() {
		return this.h256;
	}

	public void setH256(BigDecimal h256) {
		this.h256 = h256;
	}

	public BigDecimal getH257() {
		return this.h257;
	}

	public void setH257(BigDecimal h257) {
		this.h257 = h257;
	}

	public BigDecimal getH258() {
		return this.h258;
	}

	public void setH258(BigDecimal h258) {
		this.h258 = h258;
	}

	public BigDecimal getH267() {
		return this.h267;
	}

	public void setH267(BigDecimal h267) {
		this.h267 = h267;
	}

	public BigDecimal getH268() {
		return this.h268;
	}

	public void setH268(BigDecimal h268) {
		this.h268 = h268;
	}

	public BigDecimal getH278() {
		return this.h278;
	}

	public void setH278(BigDecimal h278) {
		this.h278 = h278;
	}

	public BigDecimal getH345() {
		return this.h345;
	}

	public void setH345(BigDecimal h345) {
		this.h345 = h345;
	}

	public BigDecimal getH346() {
		return this.h346;
	}

	public void setH346(BigDecimal h346) {
		this.h346 = h346;
	}

	public BigDecimal getH347() {
		return this.h347;
	}

	public void setH347(BigDecimal h347) {
		this.h347 = h347;
	}

	public BigDecimal getH348() {
		return this.h348;
	}

	public void setH348(BigDecimal h348) {
		this.h348 = h348;
	}

	public BigDecimal getH356() {
		return this.h356;
	}

	public void setH356(BigDecimal h356) {
		this.h356 = h356;
	}

	public BigDecimal getH357() {
		return this.h357;
	}

	public void setH357(BigDecimal h357) {
		this.h357 = h357;
	}

	public BigDecimal getH358() {
		return this.h358;
	}

	public void setH358(BigDecimal h358) {
		this.h358 = h358;
	}

	public BigDecimal getH367() {
		return this.h367;
	}

	public void setH367(BigDecimal h367) {
		this.h367 = h367;
	}

	public BigDecimal getH368() {
		return this.h368;
	}

	public void setH368(BigDecimal h368) {
		this.h368 = h368;
	}

	public BigDecimal getH378() {
		return this.h378;
	}

	public void setH378(BigDecimal h378) {
		this.h378 = h378;
	}

	public BigDecimal getH456() {
		return this.h456;
	}

	public void setH456(BigDecimal h456) {
		this.h456 = h456;
	}

	public BigDecimal getH457() {
		return this.h457;
	}

	public void setH457(BigDecimal h457) {
		this.h457 = h457;
	}

	public BigDecimal getH458() {
		return this.h458;
	}

	public void setH458(BigDecimal h458) {
		this.h458 = h458;
	}

	public BigDecimal getH467() {
		return this.h467;
	}

	public void setH467(BigDecimal h467) {
		this.h467 = h467;
	}

	public BigDecimal getH468() {
		return this.h468;
	}

	public void setH468(BigDecimal h468) {
		this.h468 = h468;
	}

	public BigDecimal getH478() {
		return this.h478;
	}

	public void setH478(BigDecimal h478) {
		this.h478 = h478;
	}

	public BigDecimal getH567() {
		return this.h567;
	}

	public void setH567(BigDecimal h567) {
		this.h567 = h567;
	}

	public BigDecimal getH568() {
		return this.h568;
	}

	public void setH568(BigDecimal h568) {
		this.h568 = h568;
	}

	public BigDecimal getH578() {
		return this.h578;
	}

	public void setH578(BigDecimal h578) {
		this.h578 = h578;
	}

	public BigDecimal getH678() {
		return this.h678;
	}

	public void setH678(BigDecimal h678) {
		this.h678 = h678;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public Boolean getCorruptedOdds() {
		return this.corruptedOdds;
	}

	public void setCorruptedOdds(Boolean corruptedOdds) {
		this.corruptedOdds = corruptedOdds;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getReturnSales() {
		return this.returnSales;
	}

	public void setReturnSales(Integer returnSales) {
		this.returnSales = returnSales;
	}

	public Integer getNetsales() {
		return this.netsales;
	}

	public void setNetsales(Integer netsales) {
		this.netsales = netsales;
	}

}
