package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutoRaceLiveTiId generated by hbm2java
 */
public class AutoRaceLiveTiId implements java.io.Serializable {

	private long raceId;
	private Date timeStamp;
	private byte clothNo;

	public AutoRaceLiveTiId() {
	}

	public AutoRaceLiveTiId(long raceId, Date timeStamp, byte clothNo) {
		this.raceId = raceId;
		this.timeStamp = timeStamp;
		this.clothNo = clothNo;
	}

	public long getRaceId() {
		return this.raceId;
	}

	public void setRaceId(long raceId) {
		this.raceId = raceId;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public byte getClothNo() {
		return this.clothNo;
	}

	public void setClothNo(byte clothNo) {
		this.clothNo = clothNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutoRaceLiveTiId))
			return false;
		AutoRaceLiveTiId castOther = (AutoRaceLiveTiId) other;

		return (this.getRaceId() == castOther.getRaceId())
				&& ((this.getTimeStamp() == castOther.getTimeStamp()) || (this
						.getTimeStamp() != null
						&& castOther.getTimeStamp() != null && this
						.getTimeStamp().equals(castOther.getTimeStamp())))
				&& (this.getClothNo() == castOther.getClothNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRaceId();
		result = 37 * result
				+ (getTimeStamp() == null ? 0 : this.getTimeStamp().hashCode());
		result = 37 * result + this.getClothNo();
		return result;
	}

}
