package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutoRacePostRaceRace generated by hbm2java
 */
public class AutoRacePostRaceRace implements java.io.Serializable {

	private long raceId;
	private Long uraceId;
	private Byte raceNo;
	private Date raceDate;
	private Short trackId;
	private String trackName;
	private String actualStartTime;
	private String raceName;
	private String raceDesc;
	private Integer classId;
	private String className;
	private String raceCategory;
	private String noOfRound;
	private Integer distance;
	private String grade;
	private String weather;
	private String temperatureTrack;
	private String temperature;
	private String humidity;
	private String going;
	private String trophy;
	private Boolean cancelled;
	private Byte totalMeetingDay;
	private String bettypeNameList;
	private Date extractTime;

	public AutoRacePostRaceRace() {
	}

	public AutoRacePostRaceRace(long raceId) {
		this.raceId = raceId;
	}

	public AutoRacePostRaceRace(long raceId, Long uraceId, Byte raceNo,
			Date raceDate, Short trackId, String trackName,
			String actualStartTime, String raceName, String raceDesc,
			Integer classId, String className, String raceCategory,
			String noOfRound, Integer distance, String grade, String weather,
			String temperatureTrack, String temperature, String humidity,
			String going, String trophy, Boolean cancelled,
			Byte totalMeetingDay, String bettypeNameList, Date extractTime) {
		this.raceId = raceId;
		this.uraceId = uraceId;
		this.raceNo = raceNo;
		this.raceDate = raceDate;
		this.trackId = trackId;
		this.trackName = trackName;
		this.actualStartTime = actualStartTime;
		this.raceName = raceName;
		this.raceDesc = raceDesc;
		this.classId = classId;
		this.className = className;
		this.raceCategory = raceCategory;
		this.noOfRound = noOfRound;
		this.distance = distance;
		this.grade = grade;
		this.weather = weather;
		this.temperatureTrack = temperatureTrack;
		this.temperature = temperature;
		this.humidity = humidity;
		this.going = going;
		this.trophy = trophy;
		this.cancelled = cancelled;
		this.totalMeetingDay = totalMeetingDay;
		this.bettypeNameList = bettypeNameList;
		this.extractTime = extractTime;
	}

	public long getRaceId() {
		return this.raceId;
	}

	public void setRaceId(long raceId) {
		this.raceId = raceId;
	}

	public Long getUraceId() {
		return this.uraceId;
	}

	public void setUraceId(Long uraceId) {
		this.uraceId = uraceId;
	}

	public Byte getRaceNo() {
		return this.raceNo;
	}

	public void setRaceNo(Byte raceNo) {
		this.raceNo = raceNo;
	}

	public Date getRaceDate() {
		return this.raceDate;
	}

	public void setRaceDate(Date raceDate) {
		this.raceDate = raceDate;
	}

	public Short getTrackId() {
		return this.trackId;
	}

	public void setTrackId(Short trackId) {
		this.trackId = trackId;
	}

	public String getTrackName() {
		return this.trackName;
	}

	public void setTrackName(String trackName) {
		this.trackName = trackName;
	}

	public String getActualStartTime() {
		return this.actualStartTime;
	}

	public void setActualStartTime(String actualStartTime) {
		this.actualStartTime = actualStartTime;
	}

	public String getRaceName() {
		return this.raceName;
	}

	public void setRaceName(String raceName) {
		this.raceName = raceName;
	}

	public String getRaceDesc() {
		return this.raceDesc;
	}

	public void setRaceDesc(String raceDesc) {
		this.raceDesc = raceDesc;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getRaceCategory() {
		return this.raceCategory;
	}

	public void setRaceCategory(String raceCategory) {
		this.raceCategory = raceCategory;
	}

	public String getNoOfRound() {
		return this.noOfRound;
	}

	public void setNoOfRound(String noOfRound) {
		this.noOfRound = noOfRound;
	}

	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public String getTemperatureTrack() {
		return this.temperatureTrack;
	}

	public void setTemperatureTrack(String temperatureTrack) {
		this.temperatureTrack = temperatureTrack;
	}

	public String getTemperature() {
		return this.temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	public String getHumidity() {
		return this.humidity;
	}

	public void setHumidity(String humidity) {
		this.humidity = humidity;
	}

	public String getGoing() {
		return this.going;
	}

	public void setGoing(String going) {
		this.going = going;
	}

	public String getTrophy() {
		return this.trophy;
	}

	public void setTrophy(String trophy) {
		this.trophy = trophy;
	}

	public Boolean getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(Boolean cancelled) {
		this.cancelled = cancelled;
	}

	public Byte getTotalMeetingDay() {
		return this.totalMeetingDay;
	}

	public void setTotalMeetingDay(Byte totalMeetingDay) {
		this.totalMeetingDay = totalMeetingDay;
	}

	public String getBettypeNameList() {
		return this.bettypeNameList;
	}

	public void setBettypeNameList(String bettypeNameList) {
		this.bettypeNameList = bettypeNameList;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	@Override
	public String toString() {
		return "AutoRacePostRaceRace [raceId=" + raceId + ", uraceId=" + uraceId + ", raceNo=" + raceNo + ", raceDate="
				+ raceDate + ", trackId=" + trackId + ", trackName=" + trackName + ", actualStartTime="
				+ actualStartTime + ", raceName=" + raceName + ", raceDesc=" + raceDesc + ", classId=" + classId
				+ ", className=" + className + ", raceCategory=" + raceCategory + ", noOfRound=" + noOfRound
				+ ", distance=" + distance + ", grade=" + grade + ", weather=" + weather + ", temperatureTrack="
				+ temperatureTrack + ", temperature=" + temperature + ", humidity=" + humidity + ", going=" + going
				+ ", trophy=" + trophy + ", cancelled=" + cancelled + ", totalMeetingDay=" + totalMeetingDay
				+ ", bettypeNameList=" + bettypeNameList + ", extractTime=" + extractTime + "]";
	}

}
