package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceLiveTi generated by hbm2java
 */
public class AutoRaceLiveTi implements java.io.Serializable {

	private AutoRaceLiveTiId id;
	private Boolean isFinal;
	private BigDecimal h12;
	private BigDecimal h13;
	private BigDecimal h14;
	private BigDecimal h15;
	private BigDecimal h16;
	private BigDecimal h17;
	private BigDecimal h18;
	private BigDecimal h21;
	private BigDecimal h23;
	private BigDecimal h24;
	private BigDecimal h25;
	private BigDecimal h26;
	private BigDecimal h27;
	private BigDecimal h28;
	private BigDecimal h31;
	private BigDecimal h32;
	private BigDecimal h34;
	private BigDecimal h35;
	private BigDecimal h36;
	private BigDecimal h37;
	private BigDecimal h38;
	private BigDecimal h41;
	private BigDecimal h42;
	private BigDecimal h43;
	private BigDecimal h45;
	private BigDecimal h46;
	private BigDecimal h47;
	private BigDecimal h48;
	private BigDecimal h51;
	private BigDecimal h52;
	private BigDecimal h53;
	private BigDecimal h54;
	private BigDecimal h56;
	private BigDecimal h57;
	private BigDecimal h58;
	private BigDecimal h61;
	private BigDecimal h62;
	private BigDecimal h63;
	private BigDecimal h64;
	private BigDecimal h65;
	private BigDecimal h67;
	private BigDecimal h68;
	private BigDecimal h71;
	private BigDecimal h72;
	private BigDecimal h73;
	private BigDecimal h74;
	private BigDecimal h75;
	private BigDecimal h76;
	private BigDecimal h78;
	private BigDecimal h81;
	private BigDecimal h82;
	private BigDecimal h83;
	private BigDecimal h84;
	private BigDecimal h85;
	private BigDecimal h86;
	private BigDecimal h87;
	private Date extractTime;
	private Boolean corruptedOdds;
	private Integer sales;
	private Integer returnSales;
	private Integer netsales;

	public AutoRaceLiveTi() {
	}

	public AutoRaceLiveTi(AutoRaceLiveTiId id) {
		this.id = id;
	}

	public AutoRaceLiveTi(AutoRaceLiveTiId id, Boolean isFinal, BigDecimal h12,
			BigDecimal h13, BigDecimal h14, BigDecimal h15, BigDecimal h16,
			BigDecimal h17, BigDecimal h18, BigDecimal h21, BigDecimal h23,
			BigDecimal h24, BigDecimal h25, BigDecimal h26, BigDecimal h27,
			BigDecimal h28, BigDecimal h31, BigDecimal h32, BigDecimal h34,
			BigDecimal h35, BigDecimal h36, BigDecimal h37, BigDecimal h38,
			BigDecimal h41, BigDecimal h42, BigDecimal h43, BigDecimal h45,
			BigDecimal h46, BigDecimal h47, BigDecimal h48, BigDecimal h51,
			BigDecimal h52, BigDecimal h53, BigDecimal h54, BigDecimal h56,
			BigDecimal h57, BigDecimal h58, BigDecimal h61, BigDecimal h62,
			BigDecimal h63, BigDecimal h64, BigDecimal h65, BigDecimal h67,
			BigDecimal h68, BigDecimal h71, BigDecimal h72, BigDecimal h73,
			BigDecimal h74, BigDecimal h75, BigDecimal h76, BigDecimal h78,
			BigDecimal h81, BigDecimal h82, BigDecimal h83, BigDecimal h84,
			BigDecimal h85, BigDecimal h86, BigDecimal h87, Date extractTime,
			Boolean corruptedOdds, Integer sales, Integer returnSales,
			Integer netsales) {
		this.id = id;
		this.isFinal = isFinal;
		this.h12 = h12;
		this.h13 = h13;
		this.h14 = h14;
		this.h15 = h15;
		this.h16 = h16;
		this.h17 = h17;
		this.h18 = h18;
		this.h21 = h21;
		this.h23 = h23;
		this.h24 = h24;
		this.h25 = h25;
		this.h26 = h26;
		this.h27 = h27;
		this.h28 = h28;
		this.h31 = h31;
		this.h32 = h32;
		this.h34 = h34;
		this.h35 = h35;
		this.h36 = h36;
		this.h37 = h37;
		this.h38 = h38;
		this.h41 = h41;
		this.h42 = h42;
		this.h43 = h43;
		this.h45 = h45;
		this.h46 = h46;
		this.h47 = h47;
		this.h48 = h48;
		this.h51 = h51;
		this.h52 = h52;
		this.h53 = h53;
		this.h54 = h54;
		this.h56 = h56;
		this.h57 = h57;
		this.h58 = h58;
		this.h61 = h61;
		this.h62 = h62;
		this.h63 = h63;
		this.h64 = h64;
		this.h65 = h65;
		this.h67 = h67;
		this.h68 = h68;
		this.h71 = h71;
		this.h72 = h72;
		this.h73 = h73;
		this.h74 = h74;
		this.h75 = h75;
		this.h76 = h76;
		this.h78 = h78;
		this.h81 = h81;
		this.h82 = h82;
		this.h83 = h83;
		this.h84 = h84;
		this.h85 = h85;
		this.h86 = h86;
		this.h87 = h87;
		this.extractTime = extractTime;
		this.corruptedOdds = corruptedOdds;
		this.sales = sales;
		this.returnSales = returnSales;
		this.netsales = netsales;
	}

	public AutoRaceLiveTiId getId() {
		return this.id;
	}

	public void setId(AutoRaceLiveTiId id) {
		this.id = id;
	}

	public Boolean getIsFinal() {
		return this.isFinal;
	}

	public void setIsFinal(Boolean isFinal) {
		this.isFinal = isFinal;
	}

	public BigDecimal getH12() {
		return this.h12;
	}

	public void setH12(BigDecimal h12) {
		this.h12 = h12;
	}

	public BigDecimal getH13() {
		return this.h13;
	}

	public void setH13(BigDecimal h13) {
		this.h13 = h13;
	}

	public BigDecimal getH14() {
		return this.h14;
	}

	public void setH14(BigDecimal h14) {
		this.h14 = h14;
	}

	public BigDecimal getH15() {
		return this.h15;
	}

	public void setH15(BigDecimal h15) {
		this.h15 = h15;
	}

	public BigDecimal getH16() {
		return this.h16;
	}

	public void setH16(BigDecimal h16) {
		this.h16 = h16;
	}

	public BigDecimal getH17() {
		return this.h17;
	}

	public void setH17(BigDecimal h17) {
		this.h17 = h17;
	}

	public BigDecimal getH18() {
		return this.h18;
	}

	public void setH18(BigDecimal h18) {
		this.h18 = h18;
	}

	public BigDecimal getH21() {
		return this.h21;
	}

	public void setH21(BigDecimal h21) {
		this.h21 = h21;
	}

	public BigDecimal getH23() {
		return this.h23;
	}

	public void setH23(BigDecimal h23) {
		this.h23 = h23;
	}

	public BigDecimal getH24() {
		return this.h24;
	}

	public void setH24(BigDecimal h24) {
		this.h24 = h24;
	}

	public BigDecimal getH25() {
		return this.h25;
	}

	public void setH25(BigDecimal h25) {
		this.h25 = h25;
	}

	public BigDecimal getH26() {
		return this.h26;
	}

	public void setH26(BigDecimal h26) {
		this.h26 = h26;
	}

	public BigDecimal getH27() {
		return this.h27;
	}

	public void setH27(BigDecimal h27) {
		this.h27 = h27;
	}

	public BigDecimal getH28() {
		return this.h28;
	}

	public void setH28(BigDecimal h28) {
		this.h28 = h28;
	}

	public BigDecimal getH31() {
		return this.h31;
	}

	public void setH31(BigDecimal h31) {
		this.h31 = h31;
	}

	public BigDecimal getH32() {
		return this.h32;
	}

	public void setH32(BigDecimal h32) {
		this.h32 = h32;
	}

	public BigDecimal getH34() {
		return this.h34;
	}

	public void setH34(BigDecimal h34) {
		this.h34 = h34;
	}

	public BigDecimal getH35() {
		return this.h35;
	}

	public void setH35(BigDecimal h35) {
		this.h35 = h35;
	}

	public BigDecimal getH36() {
		return this.h36;
	}

	public void setH36(BigDecimal h36) {
		this.h36 = h36;
	}

	public BigDecimal getH37() {
		return this.h37;
	}

	public void setH37(BigDecimal h37) {
		this.h37 = h37;
	}

	public BigDecimal getH38() {
		return this.h38;
	}

	public void setH38(BigDecimal h38) {
		this.h38 = h38;
	}

	public BigDecimal getH41() {
		return this.h41;
	}

	public void setH41(BigDecimal h41) {
		this.h41 = h41;
	}

	public BigDecimal getH42() {
		return this.h42;
	}

	public void setH42(BigDecimal h42) {
		this.h42 = h42;
	}

	public BigDecimal getH43() {
		return this.h43;
	}

	public void setH43(BigDecimal h43) {
		this.h43 = h43;
	}

	public BigDecimal getH45() {
		return this.h45;
	}

	public void setH45(BigDecimal h45) {
		this.h45 = h45;
	}

	public BigDecimal getH46() {
		return this.h46;
	}

	public void setH46(BigDecimal h46) {
		this.h46 = h46;
	}

	public BigDecimal getH47() {
		return this.h47;
	}

	public void setH47(BigDecimal h47) {
		this.h47 = h47;
	}

	public BigDecimal getH48() {
		return this.h48;
	}

	public void setH48(BigDecimal h48) {
		this.h48 = h48;
	}

	public BigDecimal getH51() {
		return this.h51;
	}

	public void setH51(BigDecimal h51) {
		this.h51 = h51;
	}

	public BigDecimal getH52() {
		return this.h52;
	}

	public void setH52(BigDecimal h52) {
		this.h52 = h52;
	}

	public BigDecimal getH53() {
		return this.h53;
	}

	public void setH53(BigDecimal h53) {
		this.h53 = h53;
	}

	public BigDecimal getH54() {
		return this.h54;
	}

	public void setH54(BigDecimal h54) {
		this.h54 = h54;
	}

	public BigDecimal getH56() {
		return this.h56;
	}

	public void setH56(BigDecimal h56) {
		this.h56 = h56;
	}

	public BigDecimal getH57() {
		return this.h57;
	}

	public void setH57(BigDecimal h57) {
		this.h57 = h57;
	}

	public BigDecimal getH58() {
		return this.h58;
	}

	public void setH58(BigDecimal h58) {
		this.h58 = h58;
	}

	public BigDecimal getH61() {
		return this.h61;
	}

	public void setH61(BigDecimal h61) {
		this.h61 = h61;
	}

	public BigDecimal getH62() {
		return this.h62;
	}

	public void setH62(BigDecimal h62) {
		this.h62 = h62;
	}

	public BigDecimal getH63() {
		return this.h63;
	}

	public void setH63(BigDecimal h63) {
		this.h63 = h63;
	}

	public BigDecimal getH64() {
		return this.h64;
	}

	public void setH64(BigDecimal h64) {
		this.h64 = h64;
	}

	public BigDecimal getH65() {
		return this.h65;
	}

	public void setH65(BigDecimal h65) {
		this.h65 = h65;
	}

	public BigDecimal getH67() {
		return this.h67;
	}

	public void setH67(BigDecimal h67) {
		this.h67 = h67;
	}

	public BigDecimal getH68() {
		return this.h68;
	}

	public void setH68(BigDecimal h68) {
		this.h68 = h68;
	}

	public BigDecimal getH71() {
		return this.h71;
	}

	public void setH71(BigDecimal h71) {
		this.h71 = h71;
	}

	public BigDecimal getH72() {
		return this.h72;
	}

	public void setH72(BigDecimal h72) {
		this.h72 = h72;
	}

	public BigDecimal getH73() {
		return this.h73;
	}

	public void setH73(BigDecimal h73) {
		this.h73 = h73;
	}

	public BigDecimal getH74() {
		return this.h74;
	}

	public void setH74(BigDecimal h74) {
		this.h74 = h74;
	}

	public BigDecimal getH75() {
		return this.h75;
	}

	public void setH75(BigDecimal h75) {
		this.h75 = h75;
	}

	public BigDecimal getH76() {
		return this.h76;
	}

	public void setH76(BigDecimal h76) {
		this.h76 = h76;
	}

	public BigDecimal getH78() {
		return this.h78;
	}

	public void setH78(BigDecimal h78) {
		this.h78 = h78;
	}

	public BigDecimal getH81() {
		return this.h81;
	}

	public void setH81(BigDecimal h81) {
		this.h81 = h81;
	}

	public BigDecimal getH82() {
		return this.h82;
	}

	public void setH82(BigDecimal h82) {
		this.h82 = h82;
	}

	public BigDecimal getH83() {
		return this.h83;
	}

	public void setH83(BigDecimal h83) {
		this.h83 = h83;
	}

	public BigDecimal getH84() {
		return this.h84;
	}

	public void setH84(BigDecimal h84) {
		this.h84 = h84;
	}

	public BigDecimal getH85() {
		return this.h85;
	}

	public void setH85(BigDecimal h85) {
		this.h85 = h85;
	}

	public BigDecimal getH86() {
		return this.h86;
	}

	public void setH86(BigDecimal h86) {
		this.h86 = h86;
	}

	public BigDecimal getH87() {
		return this.h87;
	}

	public void setH87(BigDecimal h87) {
		this.h87 = h87;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public Boolean getCorruptedOdds() {
		return this.corruptedOdds;
	}

	public void setCorruptedOdds(Boolean corruptedOdds) {
		this.corruptedOdds = corruptedOdds;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getReturnSales() {
		return this.returnSales;
	}

	public void setReturnSales(Integer returnSales) {
		this.returnSales = returnSales;
	}

	public Integer getNetsales() {
		return this.netsales;
	}

	public void setNetsales(Integer netsales) {
		this.netsales = netsales;
	}

}
