package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutoRacePreRaceRaceLiveId generated by hbm2java
 */
public class AutoRacePreRaceRaceLiveId implements java.io.Serializable {

	private long raceId;
	private Date extractTime;

	public AutoRacePreRaceRaceLiveId() {
	}

	public AutoRacePreRaceRaceLiveId(long raceId, Date extractTime) {
		this.raceId = raceId;
		this.extractTime = extractTime;
	}

	public long getRaceId() {
		return this.raceId;
	}

	public void setRaceId(long raceId) {
		this.raceId = raceId;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutoRacePreRaceRaceLiveId))
			return false;
		AutoRacePreRaceRaceLiveId castOther = (AutoRacePreRaceRaceLiveId) other;

		return (this.getRaceId() == castOther.getRaceId())
				&& ((this.getExtractTime() == castOther.getExtractTime()) || (this
						.getExtractTime() != null
						&& castOther.getExtractTime() != null && this
						.getExtractTime().equals(castOther.getExtractTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRaceId();
		result = 37
				* result
				+ (getExtractTime() == null ? 0 : this.getExtractTime()
						.hashCode());
		return result;
	}

}
