package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRacePreRacePlayer generated by hbm2java
 */
public class AutoRacePreRacePlayer implements java.io.Serializable {

	private AutoRacePreRacePlayerId id;
	private Long uraceId;
	private String playerName;
	private String playerNameEn;
	private Byte clothNo;
	private String lg;
	private Byte age;
	private BigDecimal handicap;
	private String playerImagePath;
	private String motorName;
	private String motorClass;
	private String period;
	private String currentRank;
	private String lastRank;
	private String examinationPoint;
	private Boolean scratch;
	private Date extractTime;
	private BigDecimal trialT;
	private BigDecimal trialOffset;
	private BigDecimal playerWeight;
	private String forcastVisual;
	private String forcastFine;
	private String forcastRain;
	private String forcastStrength;

	public AutoRacePreRacePlayer() {
	}

	public AutoRacePreRacePlayer(AutoRacePreRacePlayerId id) {
		this.id = id;
	}

	public AutoRacePreRacePlayer(AutoRacePreRacePlayerId id, Long uraceId,
			String playerName, String playerNameEn, Byte clothNo, String lg,
			Byte age, BigDecimal handicap, String playerImagePath,
			String motorName, String motorClass, String period,
			String currentRank, String lastRank, String examinationPoint,
			Boolean scratch, Date extractTime, BigDecimal trialT,
			BigDecimal trialOffset, BigDecimal playerWeight,
			String forcastVisual, String forcastFine, String forcastRain,
			String forcastStrength) {
		this.id = id;
		this.uraceId = uraceId;
		this.playerName = playerName;
		this.playerNameEn = playerNameEn;
		this.clothNo = clothNo;
		this.lg = lg;
		this.age = age;
		this.handicap = handicap;
		this.playerImagePath = playerImagePath;
		this.motorName = motorName;
		this.motorClass = motorClass;
		this.period = period;
		this.currentRank = currentRank;
		this.lastRank = lastRank;
		this.examinationPoint = examinationPoint;
		this.scratch = scratch;
		this.extractTime = extractTime;
		this.trialT = trialT;
		this.trialOffset = trialOffset;
		this.playerWeight = playerWeight;
		this.forcastVisual = forcastVisual;
		this.forcastFine = forcastFine;
		this.forcastRain = forcastRain;
		this.forcastStrength = forcastStrength;
	}

	public AutoRacePreRacePlayerId getId() {
		return this.id;
	}

	public void setId(AutoRacePreRacePlayerId id) {
		this.id = id;
	}

	public Long getUraceId() {
		return this.uraceId;
	}

	public void setUraceId(Long uraceId) {
		this.uraceId = uraceId;
	}

	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	public String getPlayerNameEn() {
		return this.playerNameEn;
	}

	public void setPlayerNameEn(String playerNameEn) {
		this.playerNameEn = playerNameEn;
	}

	public Byte getClothNo() {
		return this.clothNo;
	}

	public void setClothNo(Byte clothNo) {
		this.clothNo = clothNo;
	}

	public String getLg() {
		return this.lg;
	}

	public void setLg(String lg) {
		this.lg = lg;
	}

	public Byte getAge() {
		return this.age;
	}

	public void setAge(Byte age) {
		this.age = age;
	}

	public BigDecimal getHandicap() {
		return this.handicap;
	}

	public void setHandicap(BigDecimal handicap) {
		this.handicap = handicap;
	}

	public String getPlayerImagePath() {
		return this.playerImagePath;
	}

	public void setPlayerImagePath(String playerImagePath) {
		this.playerImagePath = playerImagePath;
	}

	public String getMotorName() {
		return this.motorName;
	}

	public void setMotorName(String motorName) {
		this.motorName = motorName;
	}

	public String getMotorClass() {
		return this.motorClass;
	}

	public void setMotorClass(String motorClass) {
		this.motorClass = motorClass;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getCurrentRank() {
		return this.currentRank;
	}

	public void setCurrentRank(String currentRank) {
		this.currentRank = currentRank;
	}

	public String getLastRank() {
		return this.lastRank;
	}

	public void setLastRank(String lastRank) {
		this.lastRank = lastRank;
	}

	public String getExaminationPoint() {
		return this.examinationPoint;
	}

	public void setExaminationPoint(String examinationPoint) {
		this.examinationPoint = examinationPoint;
	}

	public Boolean getScratch() {
		return this.scratch;
	}

	public void setScratch(Boolean scratch) {
		this.scratch = scratch;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public BigDecimal getTrialT() {
		return this.trialT;
	}

	public void setTrialT(BigDecimal trialT) {
		this.trialT = trialT;
	}

	public BigDecimal getTrialOffset() {
		return this.trialOffset;
	}

	public void setTrialOffset(BigDecimal trialOffset) {
		this.trialOffset = trialOffset;
	}

	public BigDecimal getPlayerWeight() {
		return this.playerWeight;
	}

	public void setPlayerWeight(BigDecimal playerWeight) {
		this.playerWeight = playerWeight;
	}

	public String getForcastVisual() {
		return this.forcastVisual;
	}

	public void setForcastVisual(String forcastVisual) {
		this.forcastVisual = forcastVisual;
	}

	public String getForcastFine() {
		return this.forcastFine;
	}

	public void setForcastFine(String forcastFine) {
		this.forcastFine = forcastFine;
	}

	public String getForcastRain() {
		return this.forcastRain;
	}

	public void setForcastRain(String forcastRain) {
		this.forcastRain = forcastRain;
	}

	public String getForcastStrength() {
		return this.forcastStrength;
	}

	public void setForcastStrength(String forcastStrength) {
		this.forcastStrength = forcastStrength;
	}

}
