package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AutoRaceLiveE generated by hbm2java
 */
public class AutoRaceLiveE implements java.io.Serializable {

	private AutoRaceLiveEId id;
	private Boolean isFinal;
	private BigDecimal e12;
	private BigDecimal e13;
	private BigDecimal e14;
	private BigDecimal e15;
	private BigDecimal e16;
	private BigDecimal e17;
	private BigDecimal e18;
	private BigDecimal e21;
	private BigDecimal e23;
	private BigDecimal e24;
	private BigDecimal e25;
	private BigDecimal e26;
	private BigDecimal e27;
	private BigDecimal e28;
	private BigDecimal e31;
	private BigDecimal e32;
	private BigDecimal e34;
	private BigDecimal e35;
	private BigDecimal e36;
	private BigDecimal e37;
	private BigDecimal e38;
	private BigDecimal e41;
	private BigDecimal e42;
	private BigDecimal e43;
	private BigDecimal e45;
	private BigDecimal e46;
	private BigDecimal e47;
	private BigDecimal e48;
	private BigDecimal e51;
	private BigDecimal e52;
	private BigDecimal e53;
	private BigDecimal e54;
	private BigDecimal e56;
	private BigDecimal e57;
	private BigDecimal e58;
	private BigDecimal e61;
	private BigDecimal e62;
	private BigDecimal e63;
	private BigDecimal e64;
	private BigDecimal e65;
	private BigDecimal e67;
	private BigDecimal e68;
	private BigDecimal e71;
	private BigDecimal e72;
	private BigDecimal e73;
	private BigDecimal e74;
	private BigDecimal e75;
	private BigDecimal e76;
	private BigDecimal e78;
	private BigDecimal e81;
	private BigDecimal e82;
	private BigDecimal e83;
	private BigDecimal e84;
	private BigDecimal e85;
	private BigDecimal e86;
	private BigDecimal e87;
	private Date extractTime;
	private Boolean corruptedOdds;
	private Integer sales;
	private Integer returnSales;
	private Integer netsales;

	public AutoRaceLiveE() {
	}

	public AutoRaceLiveE(AutoRaceLiveEId id) {
		this.id = id;
	}

	public AutoRaceLiveE(AutoRaceLiveEId id, Boolean isFinal, BigDecimal e12,
			BigDecimal e13, BigDecimal e14, BigDecimal e15, BigDecimal e16,
			BigDecimal e17, BigDecimal e18, BigDecimal e21, BigDecimal e23,
			BigDecimal e24, BigDecimal e25, BigDecimal e26, BigDecimal e27,
			BigDecimal e28, BigDecimal e31, BigDecimal e32, BigDecimal e34,
			BigDecimal e35, BigDecimal e36, BigDecimal e37, BigDecimal e38,
			BigDecimal e41, BigDecimal e42, BigDecimal e43, BigDecimal e45,
			BigDecimal e46, BigDecimal e47, BigDecimal e48, BigDecimal e51,
			BigDecimal e52, BigDecimal e53, BigDecimal e54, BigDecimal e56,
			BigDecimal e57, BigDecimal e58, BigDecimal e61, BigDecimal e62,
			BigDecimal e63, BigDecimal e64, BigDecimal e65, BigDecimal e67,
			BigDecimal e68, BigDecimal e71, BigDecimal e72, BigDecimal e73,
			BigDecimal e74, BigDecimal e75, BigDecimal e76, BigDecimal e78,
			BigDecimal e81, BigDecimal e82, BigDecimal e83, BigDecimal e84,
			BigDecimal e85, BigDecimal e86, BigDecimal e87, Date extractTime,
			Boolean corruptedOdds, Integer sales, Integer returnSales,
			Integer netsales) {
		this.id = id;
		this.isFinal = isFinal;
		this.e12 = e12;
		this.e13 = e13;
		this.e14 = e14;
		this.e15 = e15;
		this.e16 = e16;
		this.e17 = e17;
		this.e18 = e18;
		this.e21 = e21;
		this.e23 = e23;
		this.e24 = e24;
		this.e25 = e25;
		this.e26 = e26;
		this.e27 = e27;
		this.e28 = e28;
		this.e31 = e31;
		this.e32 = e32;
		this.e34 = e34;
		this.e35 = e35;
		this.e36 = e36;
		this.e37 = e37;
		this.e38 = e38;
		this.e41 = e41;
		this.e42 = e42;
		this.e43 = e43;
		this.e45 = e45;
		this.e46 = e46;
		this.e47 = e47;
		this.e48 = e48;
		this.e51 = e51;
		this.e52 = e52;
		this.e53 = e53;
		this.e54 = e54;
		this.e56 = e56;
		this.e57 = e57;
		this.e58 = e58;
		this.e61 = e61;
		this.e62 = e62;
		this.e63 = e63;
		this.e64 = e64;
		this.e65 = e65;
		this.e67 = e67;
		this.e68 = e68;
		this.e71 = e71;
		this.e72 = e72;
		this.e73 = e73;
		this.e74 = e74;
		this.e75 = e75;
		this.e76 = e76;
		this.e78 = e78;
		this.e81 = e81;
		this.e82 = e82;
		this.e83 = e83;
		this.e84 = e84;
		this.e85 = e85;
		this.e86 = e86;
		this.e87 = e87;
		this.extractTime = extractTime;
		this.corruptedOdds = corruptedOdds;
		this.sales = sales;
		this.returnSales = returnSales;
		this.netsales = netsales;
	}

	public AutoRaceLiveEId getId() {
		return this.id;
	}

	public void setId(AutoRaceLiveEId id) {
		this.id = id;
	}

	public Boolean getIsFinal() {
		return this.isFinal;
	}

	public void setIsFinal(Boolean isFinal) {
		this.isFinal = isFinal;
	}

	public BigDecimal getE12() {
		return this.e12;
	}

	public void setE12(BigDecimal e12) {
		this.e12 = e12;
	}

	public BigDecimal getE13() {
		return this.e13;
	}

	public void setE13(BigDecimal e13) {
		this.e13 = e13;
	}

	public BigDecimal getE14() {
		return this.e14;
	}

	public void setE14(BigDecimal e14) {
		this.e14 = e14;
	}

	public BigDecimal getE15() {
		return this.e15;
	}

	public void setE15(BigDecimal e15) {
		this.e15 = e15;
	}

	public BigDecimal getE16() {
		return this.e16;
	}

	public void setE16(BigDecimal e16) {
		this.e16 = e16;
	}

	public BigDecimal getE17() {
		return this.e17;
	}

	public void setE17(BigDecimal e17) {
		this.e17 = e17;
	}

	public BigDecimal getE18() {
		return this.e18;
	}

	public void setE18(BigDecimal e18) {
		this.e18 = e18;
	}

	public BigDecimal getE21() {
		return this.e21;
	}

	public void setE21(BigDecimal e21) {
		this.e21 = e21;
	}

	public BigDecimal getE23() {
		return this.e23;
	}

	public void setE23(BigDecimal e23) {
		this.e23 = e23;
	}

	public BigDecimal getE24() {
		return this.e24;
	}

	public void setE24(BigDecimal e24) {
		this.e24 = e24;
	}

	public BigDecimal getE25() {
		return this.e25;
	}

	public void setE25(BigDecimal e25) {
		this.e25 = e25;
	}

	public BigDecimal getE26() {
		return this.e26;
	}

	public void setE26(BigDecimal e26) {
		this.e26 = e26;
	}

	public BigDecimal getE27() {
		return this.e27;
	}

	public void setE27(BigDecimal e27) {
		this.e27 = e27;
	}

	public BigDecimal getE28() {
		return this.e28;
	}

	public void setE28(BigDecimal e28) {
		this.e28 = e28;
	}

	public BigDecimal getE31() {
		return this.e31;
	}

	public void setE31(BigDecimal e31) {
		this.e31 = e31;
	}

	public BigDecimal getE32() {
		return this.e32;
	}

	public void setE32(BigDecimal e32) {
		this.e32 = e32;
	}

	public BigDecimal getE34() {
		return this.e34;
	}

	public void setE34(BigDecimal e34) {
		this.e34 = e34;
	}

	public BigDecimal getE35() {
		return this.e35;
	}

	public void setE35(BigDecimal e35) {
		this.e35 = e35;
	}

	public BigDecimal getE36() {
		return this.e36;
	}

	public void setE36(BigDecimal e36) {
		this.e36 = e36;
	}

	public BigDecimal getE37() {
		return this.e37;
	}

	public void setE37(BigDecimal e37) {
		this.e37 = e37;
	}

	public BigDecimal getE38() {
		return this.e38;
	}

	public void setE38(BigDecimal e38) {
		this.e38 = e38;
	}

	public BigDecimal getE41() {
		return this.e41;
	}

	public void setE41(BigDecimal e41) {
		this.e41 = e41;
	}

	public BigDecimal getE42() {
		return this.e42;
	}

	public void setE42(BigDecimal e42) {
		this.e42 = e42;
	}

	public BigDecimal getE43() {
		return this.e43;
	}

	public void setE43(BigDecimal e43) {
		this.e43 = e43;
	}

	public BigDecimal getE45() {
		return this.e45;
	}

	public void setE45(BigDecimal e45) {
		this.e45 = e45;
	}

	public BigDecimal getE46() {
		return this.e46;
	}

	public void setE46(BigDecimal e46) {
		this.e46 = e46;
	}

	public BigDecimal getE47() {
		return this.e47;
	}

	public void setE47(BigDecimal e47) {
		this.e47 = e47;
	}

	public BigDecimal getE48() {
		return this.e48;
	}

	public void setE48(BigDecimal e48) {
		this.e48 = e48;
	}

	public BigDecimal getE51() {
		return this.e51;
	}

	public void setE51(BigDecimal e51) {
		this.e51 = e51;
	}

	public BigDecimal getE52() {
		return this.e52;
	}

	public void setE52(BigDecimal e52) {
		this.e52 = e52;
	}

	public BigDecimal getE53() {
		return this.e53;
	}

	public void setE53(BigDecimal e53) {
		this.e53 = e53;
	}

	public BigDecimal getE54() {
		return this.e54;
	}

	public void setE54(BigDecimal e54) {
		this.e54 = e54;
	}

	public BigDecimal getE56() {
		return this.e56;
	}

	public void setE56(BigDecimal e56) {
		this.e56 = e56;
	}

	public BigDecimal getE57() {
		return this.e57;
	}

	public void setE57(BigDecimal e57) {
		this.e57 = e57;
	}

	public BigDecimal getE58() {
		return this.e58;
	}

	public void setE58(BigDecimal e58) {
		this.e58 = e58;
	}

	public BigDecimal getE61() {
		return this.e61;
	}

	public void setE61(BigDecimal e61) {
		this.e61 = e61;
	}

	public BigDecimal getE62() {
		return this.e62;
	}

	public void setE62(BigDecimal e62) {
		this.e62 = e62;
	}

	public BigDecimal getE63() {
		return this.e63;
	}

	public void setE63(BigDecimal e63) {
		this.e63 = e63;
	}

	public BigDecimal getE64() {
		return this.e64;
	}

	public void setE64(BigDecimal e64) {
		this.e64 = e64;
	}

	public BigDecimal getE65() {
		return this.e65;
	}

	public void setE65(BigDecimal e65) {
		this.e65 = e65;
	}

	public BigDecimal getE67() {
		return this.e67;
	}

	public void setE67(BigDecimal e67) {
		this.e67 = e67;
	}

	public BigDecimal getE68() {
		return this.e68;
	}

	public void setE68(BigDecimal e68) {
		this.e68 = e68;
	}

	public BigDecimal getE71() {
		return this.e71;
	}

	public void setE71(BigDecimal e71) {
		this.e71 = e71;
	}

	public BigDecimal getE72() {
		return this.e72;
	}

	public void setE72(BigDecimal e72) {
		this.e72 = e72;
	}

	public BigDecimal getE73() {
		return this.e73;
	}

	public void setE73(BigDecimal e73) {
		this.e73 = e73;
	}

	public BigDecimal getE74() {
		return this.e74;
	}

	public void setE74(BigDecimal e74) {
		this.e74 = e74;
	}

	public BigDecimal getE75() {
		return this.e75;
	}

	public void setE75(BigDecimal e75) {
		this.e75 = e75;
	}

	public BigDecimal getE76() {
		return this.e76;
	}

	public void setE76(BigDecimal e76) {
		this.e76 = e76;
	}

	public BigDecimal getE78() {
		return this.e78;
	}

	public void setE78(BigDecimal e78) {
		this.e78 = e78;
	}

	public BigDecimal getE81() {
		return this.e81;
	}

	public void setE81(BigDecimal e81) {
		this.e81 = e81;
	}

	public BigDecimal getE82() {
		return this.e82;
	}

	public void setE82(BigDecimal e82) {
		this.e82 = e82;
	}

	public BigDecimal getE83() {
		return this.e83;
	}

	public void setE83(BigDecimal e83) {
		this.e83 = e83;
	}

	public BigDecimal getE84() {
		return this.e84;
	}

	public void setE84(BigDecimal e84) {
		this.e84 = e84;
	}

	public BigDecimal getE85() {
		return this.e85;
	}

	public void setE85(BigDecimal e85) {
		this.e85 = e85;
	}

	public BigDecimal getE86() {
		return this.e86;
	}

	public void setE86(BigDecimal e86) {
		this.e86 = e86;
	}

	public BigDecimal getE87() {
		return this.e87;
	}

	public void setE87(BigDecimal e87) {
		this.e87 = e87;
	}

	public Date getExtractTime() {
		return this.extractTime;
	}

	public void setExtractTime(Date extractTime) {
		this.extractTime = extractTime;
	}

	public Boolean getCorruptedOdds() {
		return this.corruptedOdds;
	}

	public void setCorruptedOdds(Boolean corruptedOdds) {
		this.corruptedOdds = corruptedOdds;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getReturnSales() {
		return this.returnSales;
	}

	public void setReturnSales(Integer returnSales) {
		this.returnSales = returnSales;
	}

	public Integer getNetsales() {
		return this.netsales;
	}

	public void setNetsales(Integer netsales) {
		this.netsales = netsales;
	}

}
