package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

/**
 * AutoRaceRunningPositionId generated by hbm2java
 */
public class AutoRaceRunningPositionId implements java.io.Serializable {

	private long raceid;
	private byte clothno;

	public AutoRaceRunningPositionId() {
	}

	public AutoRaceRunningPositionId(long raceid, byte clothno) {
		this.raceid = raceid;
		this.clothno = clothno;
	}

	public long getRaceid() {
		return this.raceid;
	}

	public void setRaceid(long raceid) {
		this.raceid = raceid;
	}

	public byte getClothno() {
		return this.clothno;
	}

	public void setClothno(byte clothno) {
		this.clothno = clothno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutoRaceRunningPositionId))
			return false;
		AutoRaceRunningPositionId castOther = (AutoRaceRunningPositionId) other;

		return (this.getRaceid() == castOther.getRaceid())
				&& (this.getClothno() == castOther.getClothno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRaceid();
		result = 37 * result + this.getClothno();
		return result;
	}

}
