package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutoRaceLiveTId generated by hbm2java
 */
public class AutoRaceLiveTId implements java.io.Serializable {

	private long raceId;
	private Date timeStamp;

	public AutoRaceLiveTId() {
	}

	public AutoRaceLiveTId(long raceId, Date timeStamp) {
		this.raceId = raceId;
		this.timeStamp = timeStamp;
	}

	public long getRaceId() {
		return this.raceId;
	}

	public void setRaceId(long raceId) {
		this.raceId = raceId;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutoRaceLiveTId))
			return false;
		AutoRaceLiveTId castOther = (AutoRaceLiveTId) other;

		return (this.getRaceId() == castOther.getRaceId())
				&& ((this.getTimeStamp() == castOther.getTimeStamp()) || (this
						.getTimeStamp() != null
						&& castOther.getTimeStamp() != null && this
						.getTimeStamp().equals(castOther.getTimeStamp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRaceId();
		result = 37 * result
				+ (getTimeStamp() == null ? 0 : this.getTimeStamp().hashCode());
		return result;
	}

}
