package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutoRaceRunningPosition generated by hbm2java
 */
public class AutoRaceRunningPosition implements java.io.Serializable {

	private AutoRaceRunningPositionId id;
	private Date racedate;
	private Byte pos1;
	private Byte pos2;
	private Byte pos3;
	private Byte pos4;
	private Byte pos5;
	private Byte pos6;
	private Byte pos7;
	private Byte pos8;
	private Byte pos9;
	private Byte pos10;
	private Byte finalPos;

	public AutoRaceRunningPosition() {
	}

	public AutoRaceRunningPosition(AutoRaceRunningPositionId id) {
		this.id = id;
	}

	public AutoRaceRunningPosition(AutoRaceRunningPositionId id, Date racedate,
			Byte pos1, Byte pos2, Byte pos3, Byte pos4, Byte pos5, Byte pos6,
			Byte pos7, Byte pos8, Byte pos9, Byte pos10, Byte finalPos) {
		this.id = id;
		this.racedate = racedate;
		this.pos1 = pos1;
		this.pos2 = pos2;
		this.pos3 = pos3;
		this.pos4 = pos4;
		this.pos5 = pos5;
		this.pos6 = pos6;
		this.pos7 = pos7;
		this.pos8 = pos8;
		this.pos9 = pos9;
		this.pos10 = pos10;
		this.finalPos = finalPos;
	}

	public AutoRaceRunningPositionId getId() {
		return this.id;
	}

	public void setId(AutoRaceRunningPositionId id) {
		this.id = id;
	}

	public Date getRacedate() {
		return this.racedate;
	}

	public void setRacedate(Date racedate) {
		this.racedate = racedate;
	}

	public Byte getPos1() {
		return this.pos1;
	}

	public void setPos1(Byte pos1) {
		this.pos1 = pos1;
	}

	public Byte getPos2() {
		return this.pos2;
	}

	public void setPos2(Byte pos2) {
		this.pos2 = pos2;
	}

	public Byte getPos3() {
		return this.pos3;
	}

	public void setPos3(Byte pos3) {
		this.pos3 = pos3;
	}

	public Byte getPos4() {
		return this.pos4;
	}

	public void setPos4(Byte pos4) {
		this.pos4 = pos4;
	}

	public Byte getPos5() {
		return this.pos5;
	}

	public void setPos5(Byte pos5) {
		this.pos5 = pos5;
	}

	public Byte getPos6() {
		return this.pos6;
	}

	public void setPos6(Byte pos6) {
		this.pos6 = pos6;
	}

	public Byte getPos7() {
		return this.pos7;
	}

	public void setPos7(Byte pos7) {
		this.pos7 = pos7;
	}

	public Byte getPos8() {
		return this.pos8;
	}

	public void setPos8(Byte pos8) {
		this.pos8 = pos8;
	}

	public Byte getPos9() {
		return this.pos9;
	}

	public void setPos9(Byte pos9) {
		this.pos9 = pos9;
	}

	public Byte getPos10() {
		return this.pos10;
	}

	public void setPos10(Byte pos10) {
		this.pos10 = pos10;
	}

	public Byte getFinalPos() {
		return this.finalPos;
	}

	public void setFinalPos(Byte finalPos) {
		this.finalPos = finalPos;
	}

}
