package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * CodePlayer generated by hbm2java
 */
public class CodePlayer implements java.io.Serializable {

	private int playerId;
	private String playerName;
	private String playerNameEn;
	private String playerOrigin;
	private Date playerBirthday;
	private Date registrationDate;
	private Integer registrationNo;
	private String period;
	private String lg;
	private String ownedCar;
	private BigDecimal playerHeight;
	private BigDecimal playerWeight;
	private String bloodType;
	private String constellation;
	private String hobby;

	public CodePlayer() {
	}

	public CodePlayer(int playerId) {
		this.playerId = playerId;
	}

	public CodePlayer(int playerId, String playerName, String playerNameEn,
			String playerOrigin, Date playerBirthday, Date registrationDate,
			Integer registrationNo, String period, String lg, String ownedCar,
			BigDecimal playerHeight, BigDecimal playerWeight, String bloodType,
			String constellation, String hobby) {
		this.playerId = playerId;
		this.playerName = playerName;
		this.playerNameEn = playerNameEn;
		this.playerOrigin = playerOrigin;
		this.playerBirthday = playerBirthday;
		this.registrationDate = registrationDate;
		this.registrationNo = registrationNo;
		this.period = period;
		this.lg = lg;
		this.ownedCar = ownedCar;
		this.playerHeight = playerHeight;
		this.playerWeight = playerWeight;
		this.bloodType = bloodType;
		this.constellation = constellation;
		this.hobby = hobby;
	}

	public int getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(int playerId) {
		this.playerId = playerId;
	}
	
	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName =playerName;
	}

	public String getPlayerNameEn() {
		return this.playerNameEn;
	}

	public void setPlayerNameEn(String playerNameEn) {
		this.playerNameEn = playerNameEn;
	}

	public String getPlayerOrigin() {
		return this.playerOrigin;
	}

	public void setPlayerOrigin(String playerOrigin) {
		this.playerOrigin = playerOrigin;
	}

	public Date getPlayerBirthday() {
		return this.playerBirthday;
	}

	public void setPlayerBirthday(Date playerBirthday) {
		this.playerBirthday = playerBirthday;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Integer getRegistrationNo() {
		return this.registrationNo;
	}

	public void setRegistrationNo(Integer registrationNo) {
		this.registrationNo = registrationNo;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getLg() {
		return this.lg;
	}

	public void setLg(String lg) {
		this.lg = lg;
	}

	public String getOwnedCar() {
		return this.ownedCar;
	}

	public void setOwnedCar(String ownedCar) {
		this.ownedCar = ownedCar;
	}

	public BigDecimal getPlayerHeight() {
		return this.playerHeight;
	}

	public void setPlayerHeight(BigDecimal playerHeight) {
		this.playerHeight = playerHeight;
	}

	public BigDecimal getPlayerWeight() {
		return this.playerWeight;
	}

	public void setPlayerWeight(BigDecimal playerWeight) {
		this.playerWeight = playerWeight;
	}

	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getConstellation() {
		return this.constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

}
