package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

/**
 * CodeBetTypeId generated by hbm2java
 */
public class CodeBetTypeId implements java.io.Serializable {

	private byte betTypeId;
	private String betTypeName;
	private String rawBetType;

	public CodeBetTypeId() {
	}

	public CodeBetTypeId(byte betTypeId) {
		this.betTypeId = betTypeId;
	}

	public CodeBetTypeId(byte betTypeId, String betTypeName, String rawBetType) {
		this.betTypeId = betTypeId;
		this.betTypeName = betTypeName;
		this.rawBetType = rawBetType;
	}

	public byte getBetTypeId() {
		return this.betTypeId;
	}

	public void setBetTypeId(byte betTypeId) {
		this.betTypeId = betTypeId;
	}

	public String getBetTypeName() {
		return this.betTypeName;
	}

	public void setBetTypeName(String betTypeName) {
		this.betTypeName = betTypeName;
	}

	public String getRawBetType() {
		return this.rawBetType;
	}

	public void setRawBetType(String rawBetType) {
		this.rawBetType = rawBetType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodeBetTypeId))
			return false;
		CodeBetTypeId castOther = (CodeBetTypeId) other;

		return (this.getBetTypeId() == castOther.getBetTypeId())
				&& ((this.getBetTypeName() == castOther.getBetTypeName()) || (this
						.getBetTypeName() != null
						&& castOther.getBetTypeName() != null && this
						.getBetTypeName().equals(castOther.getBetTypeName())))
				&& ((this.getRawBetType() == castOther.getRawBetType()) || (this
						.getRawBetType() != null
						&& castOther.getRawBetType() != null && this
						.getRawBetType().equals(castOther.getRawBetType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBetTypeId();
		result = 37
				* result
				+ (getBetTypeName() == null ? 0 : this.getBetTypeName()
						.hashCode());
		result = 37
				* result
				+ (getRawBetType() == null ? 0 : this.getRawBetType()
						.hashCode());
		return result;
	}

}
