package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

/**
 * CodeTrack generated by hbm2java
 */
public class CodeTrack implements java.io.Serializable {

	private short trackId;
	private String trackName;
	private String englishName;

	public CodeTrack() {
	}

	public CodeTrack(short trackId) {
		this.trackId = trackId;
	}

	public CodeTrack(short trackId, String trackName, String englishName) {
		this.trackId = trackId;
		this.trackName = trackName;
		this.englishName = englishName;
	}

	public short getTrackId() {
		return this.trackId;
	}

	public void setTrackId(short trackId) {
		this.trackId = trackId;
	}

	public String getTrackName() {
		return this.trackName;
	}

	public void setTrackName(String trackName) {
		this.trackName = trackName;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

}
