package jp.autorace.dc;

// Generated 2015-10-13 3:28:11 by Hibernate Tools 3.4.0.CR1

/**
 * CodeBetType generated by hbm2java
 */
public class CodeBetType implements java.io.Serializable {

	private CodeBetTypeId id;

	public CodeBetType() {
	}

	public CodeBetType(CodeBetTypeId id) {
		this.id = id;
	}

	public CodeBetTypeId getId() {
		return this.id;
	}

	public void setId(CodeBetTypeId id) {
		this.id = id;
	}

}
